name: build-website

on: 
    workflow_call:

jobs:
    build-application:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Install .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 3.1 

        - name: Build publishable application
          run: |
            dotnet publish --configuration Release
          working-directory: src/ToyCompany/ToyCompany.Website

        - name: Zip publishable website
          run: |
            zip -r publish.zip .
            working-directory: ./src/ToyCompany/ToyCompany.Website/bin/Release/netcoreapp3.1/publish

        - name: Upload webstie as workflow artifact
          uses: actions/upload-artifact@v4
          with: 
            name: website
            path: ./src/ToyCompany/ToyCompany.Website/bin/Release/netcoreapp3.1/publish