name: build-website

on: 
    workflow_call:

jobs:
    build-application:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Install .NET Core
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Build publishable application
          run: dotnet publish --configuration Release
          working-directory: src/ToyCompany/ToyCompany.Website

        - name: Zip publishable website
          run: zip -r publish.zip .
          working-directory: ./src/ToyCompany/ToyCompany.Website/bin/Release/net8.0/publish

        - name: Upload website as workflow artifact
          uses: actions/upload-artifact@v4
          with: 
            name: website
            path: ./src/ToyCompany/ToyCompany.Website/bin/Release/net8.0/publish/publish.zip
            
    build-database:
        name: Build database
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v3

        - name: Prepare MSBuild
          uses: microsoft/setup-msbuild@v1.1

        - name: Build database project
          working-directory: src/ToyCompany/ToyCompany.Database
          run: MSBuild.exe ToyCompany.Database.sqlproj -property:Configuration=Release

        - name: Upload database as workflow artifact
          uses: actions/upload-artifact@v4
          with: 
            name: database
            path: ./src/ToyCompany/ToyCompany.Database/bin/Release/ToyCompany.Database.dacpac
